### ISSUE TITLE
Digital I/O

### ISSUE THREAD

**Issue by nicholaslwagner** [NOAA-CSD/soap#27]
In the datafile and in UI when communication with the honeywells, alicats, and vaisala RH probe drop out, could the UI write a valve like -9999 to the UI and datafile instead of zero?

This change will make it easier to filter out bad data.

**Comment by lo-co** [comment]
I think we need to get rid of these dropouts period.  We will work on this when it comes back.

But here is another question - do you want the data to go stale or do you want to have the -9999 in the file? i.e. do you want the data to just not refresh if it doesn't come back ok?

**Comment by nicholaslwagner** [comment]
I would like to put -9999 in the data file.

**Comment by lo-co** [comment]
Will do.
