### ISSUE TITLE
Set up Raspberry Pi

### ISSUE THREAD

**Issue by nicholaslwagner** [NOAA-CSD/soap#39]
1) Clear errors on start up
2) set resolution for AMPrack display
3) setup webbrowser to open on startup and open the SOAP webpage/instrument control

**Comment by lo-co** [comment]
We have the technique to do this.  These values are set at the bottom of `/boot/config.txt`.  Browser is set to come up on login and the page that is opened is at `10.172.240.107:8080/soap`.

Welcome menu will not come up on login anymore.
